#!/bin/bash
# Recreate my zsh shell setup on a fresh Mac:
#   - native vcs_info prompt (cwd + git branch, clock on the right)
#   - history, case-insensitive menu completion
#   - zsh-autosuggestions, zsh-syntax-highlighting, fzf, zoxide (via Homebrew)
#   - iTerm2 with my profile (Monaco 15, light colour scheme) set as default
# Usage:
#   ./recreate-mac-shell.sh              # install deps + write ~/.zshrc
#   ./recreate-mac-shell.sh --no-install # skip Homebrew/package/iTerm2 installs
# Any existing ~/.zshrc is backed up to ~/.zshrc.bak.<timestamp>.
set -euo pipefail

ZSHRC="$HOME/.zshrc"
ZPROFILE="$HOME/.zprofile"
ITERM_PROFILE_DIR="$HOME/Library/Application Support/iTerm2/DynamicProfiles"
ITERM_PROFILE_GUID="7E1A3C52-5B1F-4C8E-9D2A-3F6B8E0C1A47"

install_deps=true
if [ "${1:-}" = "--no-install" ]; then install_deps=false; fi

if [ "$(uname)" != "Darwin" ]; then
  echo "ERROR: this script is for macOS." >&2
  exit 1
fi

# --- STEP 1: Homebrew + packages ---
if $install_deps; then
  if ! command -v brew >/dev/null 2>&1; then
    for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
      [ -x "$b" ] && eval "$("$b" shellenv)" && break
    done
  fi
  if ! command -v brew >/dev/null 2>&1; then
    echo "Installing Homebrew..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    for b in /opt/homebrew/bin/brew /usr/local/bin/brew; do
      [ -x "$b" ] && eval "$("$b" shellenv)" && break
    done
  fi

  # Make brew available in login shells (Homebrew's installer only prints this step)
  BREW_BIN="$(command -v brew)"
  if ! grep -qs 'brew shellenv' "$ZPROFILE"; then
    echo "eval \"\$($BREW_BIN shellenv)\"" >> "$ZPROFILE"
    echo "Added brew shellenv -> $ZPROFILE"
  fi

  echo "Installing shell packages..."
  brew install zsh-autosuggestions zsh-syntax-highlighting fzf zoxide
  if [ ! -d /Applications/iTerm.app ]; then
    brew install --cask iterm2
  fi
fi

# --- STEP 2: backup existing ~/.zshrc ---
if [ -f "$ZSHRC" ]; then
  BACKUP="$ZSHRC.bak.$(date +%Y%m%d-%H%M%S)"
  cp "$ZSHRC" "$BACKUP"
  echo "Backed up $ZSHRC -> $BACKUP"
fi

# --- STEP 3: write ~/.zshrc ---
cat > "$ZSHRC" <<'EOF'
# ~/.zshrc — generated by useful-scripts/recreate-mac-shell.sh
# Minimal native prompt (vcs_info) + recommended shell superpowers.
# Sections: PATH, history, completion, prompt, plugins, QoL.

# --- PATH ---
export PATH="$HOME/.local/bin:$PATH"

# --- History ---
HISTFILE=~/.zsh_history
HISTSIZE=10000
SAVEHIST=10000
setopt share_history hist_ignore_dups hist_ignore_space hist_reduce_blanks

# --- Completion (the tab-completion upgrade) ---
autoload -Uz compinit && compinit
zstyle ':completion:*' matcher-list 'm:{a-z}={A-Z}' 'r:|=*' 'l:|=* r:|=*'
zstyle ':completion:*' menu select
zstyle ':completion:*' list-colors "${(s.:.)LS_COLORS}"
zstyle ':completion:*' complete_in_word true
zstyle ':completion:*' always_to_end true
setopt complete_in_word always_to_end auto_menu
unsetopt menu_complete

# --- Prompt: cwd + git branch, zero dependencies ---
autoload -Uz vcs_info
setopt prompt_subst
zstyle ':vcs_info:*' enable git
zstyle ':vcs_info:git:*' formats ' (%b%c%u)'
zstyle ':vcs_info:git:*' actionformats ' (%b|%a%c%u)'
zstyle ':vcs_info:git:*' check-for-changes true
zstyle ':vcs_info:git:*' stagedstr '+'
zstyle ':vcs_info:git:*' unstagedstr '*'
precmd() { vcs_info }
PROMPT='%F{cyan}%2~%f%F{green}${vcs_info_msg_0_}%f
%F{yellow}%#%f '
RPROMPT='%F{240}%*%f'

# --- Plugins (brew paths via prefix, no hardcoding) ---
if command -v brew >/dev/null; then
  BREW_PREFIX="$(brew --prefix)"
  if [[ -r "$BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh" ]]; then
    source "$BREW_PREFIX/share/zsh-autosuggestions/zsh-autosuggestions.zsh"
  fi
fi
if command -v fzf >/dev/null; then
  source <(fzf --zsh)
fi
if command -v zoxide >/dev/null; then
  eval "$(zoxide init zsh)"
fi
# syntax-highlighting must load after all widgets (incl. fzf/zoxide) define theirs
if [[ -n "$BREW_PREFIX" && -r "$BREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh" ]]; then
  source "$BREW_PREFIX/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh"
fi

# --- QoL ---
setopt auto_cd
unsetopt correct 2>/dev/null
alias ls='ls -G'
EOF
echo "Wrote $ZSHRC"

# --- STEP 4: iTerm2 profile (font + colours) as a Dynamic Profile ---
mkdir -p "$ITERM_PROFILE_DIR"
cat > "$ITERM_PROFILE_DIR/shell-setup.json" <<'EOF'
{
  "Profiles": [
    {
      "Name": "Shell Setup",
      "Guid": "7E1A3C52-5B1F-4C8E-9D2A-3F6B8E0C1A47",
      "Ansi 7 Color (Light)": {
        "Red Component": 0.7810397744178772,
        "Color Space": "sRGB",
        "Blue Component": 0.7810482978820801,
        "Alpha Component": 1.0,
        "Green Component": 0.7810582518577576
      },
      "Ansi 15 Color (Light)": {
        "Red Component": 0.9999960064888,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Ansi 2 Color (Light)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7607843279838562
      },
      "Bold Color": {
        "Red Component": 0.062745101749897,
        "Color Space": "sRGB",
        "Blue Component": 0.062745101749897,
        "Alpha Component": 1.0,
        "Green Component": 0.062745101749897
      },
      "Ansi 1 Color (Dark)": {
        "Red Component": 0.7074432373046875,
        "Color Space": "sRGB",
        "Blue Component": 0.16300037503242493,
        "Alpha Component": 1.0,
        "Green Component": 0.23660069704055786
      },
      "Use Bright Bold": true,
      "Ansi 9 Color (Light)": {
        "Red Component": 0.8659515380859375,
        "Color Space": "sRGB",
        "Blue Component": 0.45833224058151245,
        "Alpha Component": 1.0,
        "Green Component": 0.4752407670021057
      },
      "Ansi 8 Color (Dark)": {
        "Red Component": 0.4078176021575928,
        "Color Space": "sRGB",
        "Blue Component": 0.4078223705291748,
        "Alpha Component": 1.0,
        "Green Component": 0.40782788395881653
      },
      "Background Color": {
        "Red Component": 0.98,
        "Color Space": "sRGB",
        "Blue Component": 0.98,
        "Alpha Component": 1.0,
        "Green Component": 0.98
      },
      "Columns": 80,
      "Ansi 8 Color": {
        "Red Component": 0.4078176021575928,
        "Color Space": "sRGB",
        "Blue Component": 0.4078223705291748,
        "Alpha Component": 1.0,
        "Green Component": 0.40782788395881653
      },
      "Right Option Key Sends": 0,
      "Ansi 4 Color (Light)": {
        "Red Component": 0.15404300391674042,
        "Color Space": "sRGB",
        "Blue Component": 0.7821617722511292,
        "Alpha Component": 1.0,
        "Green Component": 0.2647435665130615
      },
      "Blinking Cursor": false,
      "Selected Text Color (Light)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Selected Text Color (Dark)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Ansi 3 Color (Dark)": {
        "Red Component": 0.7805864810943604,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7695948481559753
      },
      "Visual Bell": true,
      "Cursor Text Color": {
        "Red Component": 1.0,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Scrollback Lines": 1000,
      "Selection Color (Light)": {
        "Red Component": 0.7019608020782471,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.843137264251709
      },
      "Ansi 0 Color": {
        "Red Component": 0.0784313753247261,
        "Color Space": "sRGB",
        "Blue Component": 0.11764705926179886,
        "Alpha Component": 1.0,
        "Green Component": 0.09803921729326248
      },
      "Ansi 11 Color (Light)": {
        "Red Component": 0.9259033203125,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.8833775520324707
      },
      "Ansi 5 Color (Dark)": {
        "Red Component": 0.752197265625,
        "Color Space": "sRGB",
        "Blue Component": 0.7449436187744141,
        "Alpha Component": 1.0,
        "Green Component": 0.24931684136390686
      },
      "Cursor Text Color (Light)": {
        "Red Component": 1.0,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Silence Bell": false,
      "Rows": 25,
      "Ansi 14 Color (Dark)": {
        "Red Component": 0.3759753108024597,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.9926329255104065
      },
      "Ansi 15 Color (Dark)": {
        "Red Component": 0.9999960064888,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Ansi 0 Color (Dark)": {
        "Red Component": 0.0784313753247261,
        "Color Space": "sRGB",
        "Blue Component": 0.11764705926179886,
        "Alpha Component": 1.0,
        "Green Component": 0.09803921729326248
      },
      "Ambiguous Double Width": false,
      "Option Key Sends": 0,
      "Ansi 3 Color": {
        "Red Component": 0.7805864810943604,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7695948481559753
      },
      "Window Type": 0,
      "BM Growl": true,
      "Prompt Before Closing 2": false,
      "Selected Text Color": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Ansi 14 Color (Light)": {
        "Red Component": 0.3759753108024597,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.9926329255104065
      },
      "Cursor Guide Color (Dark)": {
        "Red Component": 0.37649588016392954,
        "Color Space": "sRGB",
        "Blue Component": 0.9409904479980469,
        "Alpha Component": 0.25,
        "Green Component": 0.8023261774920553
      },
      "Send Code When Idle": false,
      "Ansi 6 Color": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.7816620469093323,
        "Alpha Component": 1.0,
        "Green Component": 0.7742590308189392
      },
      "Jobs to Ignore": [
        "rlogin",
        "ssh",
        "slogin",
        "telnet"
      ],
      "Badge Color (Dark)": {
        "Red Component": 0.9787440299987793,
        "Color Space": "sRGB",
        "Blue Component": 0.6521859746214886,
        "Alpha Component": 0.5,
        "Green Component": 0.6521859746214886
      },
      "Cursor Color": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Vertical Spacing": 1.0,
      "Disable Window Resizing": true,
      "Close Sessions On End": true,
      "Selection Color (Dark)": {
        "Red Component": 0.7019608020782471,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.843137264251709
      },
      "Foreground Color (Light)": {
        "Red Component": 0.06274509803921569,
        "Color Space": "sRGB",
        "Blue Component": 0.06274509803921569,
        "Alpha Component": 1.0,
        "Green Component": 0.06274509803921569
      },
      "Background Color (Dark)": {
        "Red Component": 0.0806884765625,
        "Color Space": "sRGB",
        "Blue Component": 0.12103271484375,
        "Alpha Component": 1.0,
        "Green Component": 0.09911105036735535
      },
      "Ansi 9 Color": {
        "Red Component": 0.8659515380859375,
        "Color Space": "sRGB",
        "Blue Component": 0.45833224058151245,
        "Alpha Component": 1.0,
        "Green Component": 0.4752407670021057
      },
      "Ansi 14 Color": {
        "Red Component": 0.3759753108024597,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.9926329255104065
      },
      "Flashing Bell": false,
      "Use Italic Font": true,
      "Ansi 13 Color (Dark)": {
        "Red Component": 0.8821563720703125,
        "Color Space": "sRGB",
        "Blue Component": 0.8821563720703125,
        "Alpha Component": 1.0,
        "Green Component": 0.4927266538143158
      },
      "Cursor Guide Color (Light)": {
        "Red Component": 0.5233826264372965,
        "Color Space": "sRGB",
        "Blue Component": 0.8531928062438965,
        "Alpha Component": 0.25,
        "Green Component": 0.7721771862908952
      },
      "Ansi 12 Color": {
        "Red Component": 0.6534907817840576,
        "Color Space": "sRGB",
        "Blue Component": 0.9485321044921875,
        "Alpha Component": 1.0,
        "Green Component": 0.6704471707344055
      },
      "Ansi 10 Color (Light)": {
        "Red Component": 0.3450070321559906,
        "Color Space": "sRGB",
        "Blue Component": 0.5654193758964539,
        "Alpha Component": 1.0,
        "Green Component": 0.9042816162109375
      },
      "Non-ASCII Anti Aliased": true,
      "Ansi 10 Color": {
        "Red Component": 0.3450070321559906,
        "Color Space": "sRGB",
        "Blue Component": 0.5654193758964539,
        "Alpha Component": 1.0,
        "Green Component": 0.9042816162109375
      },
      "Foreground Color": {
        "Red Component": 0.062745101749897,
        "Color Space": "sRGB",
        "Blue Component": 0.062745101749897,
        "Alpha Component": 1.0,
        "Green Component": 0.062745101749897
      },
      "Link Color (Light)": {
        "Red Component": 0.1980242282152176,
        "Color Space": "sRGB",
        "Blue Component": 0.9337158203125,
        "Alpha Component": 1.0,
        "Green Component": 0.5578983426094055
      },
      "Ansi 7 Color (Dark)": {
        "Red Component": 0.7810397744178772,
        "Color Space": "sRGB",
        "Blue Component": 0.7810482978820801,
        "Alpha Component": 1.0,
        "Green Component": 0.7810582518577576
      },
      "Sync Title": false,
      "Ansi 1 Color": {
        "Red Component": 0.7074432373046875,
        "Color Space": "sRGB",
        "Blue Component": 0.16300037503242493,
        "Alpha Component": 1.0,
        "Green Component": 0.23660069704055786
      },
      "Transparency": 0.0,
      "Horizontal Spacing": 1.0,
      "Cursor Color (Dark)": {
        "Red Component": 0.9999763369560242,
        "Color Space": "sRGB",
        "Blue Component": 0.9999872446060181,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Ansi 2 Color (Dark)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7607843279838562
      },
      "Ansi 9 Color (Dark)": {
        "Red Component": 0.8659515380859375,
        "Color Space": "sRGB",
        "Blue Component": 0.45833224058151245,
        "Alpha Component": 1.0,
        "Green Component": 0.4752407670021057
      },
      "Badge Color": {
        "Red Component": 0.7461385726928711,
        "Color Space": "sRGB",
        "Blue Component": 0.11610633134841919,
        "Alpha Component": 0.5,
        "Green Component": 0.11610633134841919
      },
      "Ansi 13 Color (Light)": {
        "Red Component": 0.8821563720703125,
        "Color Space": "sRGB",
        "Blue Component": 0.8821563720703125,
        "Alpha Component": 1.0,
        "Green Component": 0.4927266538143158
      },
      "Idle Code": 0,
      "Ansi 4 Color": {
        "Red Component": 0.15404300391674042,
        "Color Space": "sRGB",
        "Blue Component": 0.7821617722511292,
        "Alpha Component": 1.0,
        "Green Component": 0.2647435665130615
      },
      "Bold Color (Dark)": {
        "Red Component": 0.9999960064888,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Ansi 4 Color (Dark)": {
        "Red Component": 0.15404300391674042,
        "Color Space": "sRGB",
        "Blue Component": 0.7821617722511292,
        "Alpha Component": 1.0,
        "Green Component": 0.2647435665130615
      },
      "Cursor Text Color (Dark)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Selection Color": {
        "Red Component": 0.7019608020782471,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 0.843137264251709
      },
      "Use Non-ASCII Font": false,
      "Badge Color (Light)": {
        "Red Component": 0.7461385726928711,
        "Color Space": "sRGB",
        "Blue Component": 0.11610633058398889,
        "Alpha Component": 0.5,
        "Green Component": 0.11610633058398889
      },
      "Character Encoding": 4,
      "Ansi 11 Color (Dark)": {
        "Red Component": 0.9259033203125,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.8833775520324707
      },
      "Bold Color (Light)": {
        "Red Component": 0.06274509803921569,
        "Color Space": "sRGB",
        "Blue Component": 0.06274509803921569,
        "Alpha Component": 1.0,
        "Green Component": 0.06274509803921569
      },
      "Ansi 12 Color (Dark)": {
        "Red Component": 0.6534907817840576,
        "Color Space": "sRGB",
        "Blue Component": 0.9485321044921875,
        "Alpha Component": 1.0,
        "Green Component": 0.6704471707344055
      },
      "Ansi 7 Color": {
        "Red Component": 0.7810397744178772,
        "Color Space": "sRGB",
        "Blue Component": 0.7810482978820801,
        "Alpha Component": 1.0,
        "Green Component": 0.7810582518577576
      },
      "Non Ascii Font": "Monaco 11",
      "Ansi 6 Color (Dark)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.7816620469093323,
        "Alpha Component": 1.0,
        "Green Component": 0.7742590308189392
      },
      "Cursor Guide Color": {
        "Red Component": 0.5233826041221619,
        "Color Space": "sRGB",
        "Blue Component": 0.8531928062438965,
        "Alpha Component": 0.25,
        "Green Component": 0.7721771597862244
      },
      "ASCII Anti Aliased": true,
      "Mouse Reporting": true,
      "Ansi 6 Color (Light)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.7816620469093323,
        "Alpha Component": 1.0,
        "Green Component": 0.7742590308189392
      },
      "Ansi 1 Color (Light)": {
        "Red Component": 0.7074432373046875,
        "Color Space": "sRGB",
        "Blue Component": 0.16300037503242493,
        "Alpha Component": 1.0,
        "Green Component": 0.23660069704055786
      },
      "Use Bold Font": true,
      "Ansi 8 Color (Light)": {
        "Red Component": 0.4078176021575928,
        "Color Space": "sRGB",
        "Blue Component": 0.4078223705291748,
        "Alpha Component": 1.0,
        "Green Component": 0.40782788395881653
      },
      "Ansi 2 Color": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7607843279838562
      },
      "Normal Font": "Monaco 15",
      "Unlimited Scrollback": false,
      "Ansi 12 Color (Light)": {
        "Red Component": 0.6534907817840576,
        "Color Space": "sRGB",
        "Blue Component": 0.9485321044921875,
        "Alpha Component": 1.0,
        "Green Component": 0.6704471707344055
      },
      "Ansi 10 Color (Dark)": {
        "Red Component": 0.3450070321559906,
        "Color Space": "sRGB",
        "Blue Component": 0.5654193758964539,
        "Alpha Component": 1.0,
        "Green Component": 0.9042816162109375
      },
      "Ansi 3 Color (Light)": {
        "Red Component": 0.7805864810943604,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.7695948481559753
      },
      "Cursor Color (Light)": {
        "Red Component": 0.0,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.0
      },
      "Ansi 15 Color": {
        "Red Component": 0.9999960064888,
        "Color Space": "sRGB",
        "Blue Component": 1.0,
        "Alpha Component": 1.0,
        "Green Component": 1.0
      },
      "Blur": false,
      "Use Separate Colors for Light and Dark Mode": true,
      "Background Color (Light)": {
        "Red Component": 0.98,
        "Color Space": "sRGB",
        "Blue Component": 0.98,
        "Alpha Component": 1.0,
        "Green Component": 0.98
      },
      "Terminal Type": "xterm-256color",
      "Ansi 13 Color": {
        "Red Component": 0.8821563720703125,
        "Color Space": "sRGB",
        "Blue Component": 0.8821563720703125,
        "Alpha Component": 1.0,
        "Green Component": 0.4927266538143158
      },
      "Ansi 5 Color (Light)": {
        "Red Component": 0.752197265625,
        "Color Space": "sRGB",
        "Blue Component": 0.7449436187744141,
        "Alpha Component": 1.0,
        "Green Component": 0.24931684136390686
      },
      "Foreground Color (Dark)": {
        "Red Component": 0.8619791269302368,
        "Color Space": "sRGB",
        "Blue Component": 0.8619885444641113,
        "Alpha Component": 1.0,
        "Green Component": 0.86199951171875
      },
      "Link Color": {
        "Red Component": 0.1980242282152176,
        "Color Space": "sRGB",
        "Blue Component": 0.9337158203125,
        "Alpha Component": 1.0,
        "Green Component": 0.5578983426094055
      },
      "Link Color (Dark)": {
        "Red Component": 0.1980242282152176,
        "Color Space": "sRGB",
        "Blue Component": 0.9337158203125,
        "Alpha Component": 1.0,
        "Green Component": 0.5578983426094055
      },
      "Ansi 11 Color": {
        "Red Component": 0.9259033203125,
        "Color Space": "sRGB",
        "Blue Component": 0.0,
        "Alpha Component": 1.0,
        "Green Component": 0.8833775520324707
      },
      "Ansi 5 Color": {
        "Red Component": 0.752197265625,
        "Color Space": "sRGB",
        "Blue Component": 0.7449436187744141,
        "Alpha Component": 1.0,
        "Green Component": 0.24931684136390686
      },
      "Ansi 0 Color (Light)": {
        "Red Component": 0.0784313753247261,
        "Color Space": "sRGB",
        "Blue Component": 0.11764705926179886,
        "Alpha Component": 1.0,
        "Green Component": 0.09803921729326248
      }
    }
  ]
}
EOF
echo "Wrote iTerm2 profile -> $ITERM_PROFILE_DIR/shell-setup.json"

# Make it the default profile. iTerm2 keeps prefs in memory, so this only sticks if it's not running.
if pgrep -fq '/Applications/iTerm.app/Contents/MacOS/iTerm2'; then
  echo "NOTE: iTerm2 is running. Profile 'Shell Setup' is available now; to make it default either"
  echo "      quit iTerm2 and re-run this script from Terminal.app, or use"
  echo "      Settings > Profiles > Shell Setup > Other Actions > Set as Default."
else
  defaults write com.googlecode.iterm2 "Default Bookmark Guid" -string "$ITERM_PROFILE_GUID"
  echo "Set 'Shell Setup' as the default iTerm2 profile."
fi

# --- STEP 5: verify ---
if zsh -n "$ZSHRC"; then
  echo "Syntax OK. Open a new terminal (or run: exec zsh) to use it."
else
  echo "WARNING: zsh reported a syntax error in $ZSHRC" >&2
  exit 1
fi
